// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMu1uIc-h5CqjABHA4DrCxLjkYo5tLqq8',
    appId: '1:714569368509:web:245fc131cd1515a0e3c8d4',
    messagingSenderId: '714569368509',
    projectId: 'missionary-calendar-ab1ad',
    authDomain: 'missionary-calendar-ab1ad.firebaseapp.com',
    storageBucket: 'missionary-calendar-ab1ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eImtRRapmvKxSDynJec5XNHoqA1RIyY',
    appId: '1:714569368509:android:9d253c4464a069f3e3c8d4',
    messagingSenderId: '714569368509',
    projectId: 'missionary-calendar-ab1ad',
    storageBucket: 'missionary-calendar-ab1ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVqrkTEhVBlzXG-NWCY4lFlTsLGm6UjE',
    appId: '1:714569368509:ios:18fbbf188bb0f8f8e3c8d4',
    messagingSenderId: '714569368509',
    projectId: 'missionary-calendar-ab1ad',
    storageBucket: 'missionary-calendar-ab1ad.appspot.com',
    iosClientId: '714569368509-10vvkt1va75p6rcg1gne2s4tiuj06125.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda',
  );
}
